CREATE DATABASE imagedb;

CREATE USER admin WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS PASSWORD 'admin';
CREATE USER searchservice WITH PASSWORD 'admin';

GRANT ALL PRIVILEGES ON DATABASE imagedb TO searchservice;